/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TalentPlacement {
  data: {
    talentId?: string;
    placement_status?: string;
    timestamp?: string;
    required?: ["talentId", "placement_status"];
  };
  source: "prohire";
  detailType: "TalentPlacement";
  eventBusName: "prohire";
}
