# TODO: need implement field validator
eventbus:
- name: smarthire
  topics:
  - name: UserLoggedIn
    schemaFile: smarthire/user-loggedin.json
- name: community
  topics: 
  - name: ArticlePosted
    schemaFile: community/post.json
  - name: ThreadCreated
    schemaFile: community/thread.json
- name: media
  topics:
  - name: VideoCreated
    schemaFile: media/video-upload.json
  archives:
  - name: VideoEvents
    retentionDays: 30
    pattern:
      source: media
      topic: VideoCreated #TODO: Support multiple topic
- name: learning
  topics:
  - name: LearningTrend
    schemaFile: learning/learning-trend.json
connectors:
- name: example1-subs-VideoCreated
  eventBusName: media
  source: media
  topic: VideoCreated
  target: lambda
  targetParams:
    lambdaSourcePath: dist/cdk/connector/example1.js
- name: example2-subs-ArticlePosted
  eventBusName: community
  source: community
  topic: ArticlePosted
  target: lambda
  targetParams:
    lambdaSourcePath: dist/cdk/connector/example2.js
- name: example-subs-ArticlePosted
  eventBusName: community
  source: community 
  topic: ArticlePosted
  target: sns
  targetParams:
    protocol: email
    subscription: kobtan@seekasia.com
- name: razaly-subs-LearningTrend
  eventBusName: learning
  source: learning 
  topic: LearningTrend
  target: sns
  targetParams:
    protocol: email
    subscription: razaly@seekasia.com
