# need implement field validator
eventbus:
- name: community
  topics:
  - name: ArticlePosted
    source: seekmax.community
  - name: ThreadCreated
    source: seekmax.community
  replays: {}
- name: media
  topics:
  - name: VideoCreated
    source: seekmax.media
  replays:
  - name: Video Events
    retentionDays: 30
    pattern:
    - source: seekmax.media
    - detail-type: VideoCreated
- name: learning
  topics: []
subscriptions:
- name: community-media-event
  eventbus: media
  source: seekmax.community
  pattern: VideoCreated
  target: lambda
