# TODO: need implement field validator
eventbus:
- name: smarthire
  topics:
  - name: UserLoggedIn
    schemaFile: smarthire/user-loggedin.json
- name: community
  topics: 
  - name: ArticlePosted
    schemaFile: community/post.json
  - name: ThreadCreated
    schemaFile: community/thread.json
- name: media
  topics:
  - name: VideoCreated
    schemaFile: media/video-upload.json
  replays:
  - name: VideoEvents
    retentionDays: 30
    pattern:
      source: media
      topic: VideoCreated
# - name: learning
#   topics: []
connectors:
- name: example1-subs-VideoCreated
  eventBusName: media
  source: media
  topic: VideoCreated
  target: lambda
  targetParams:
    lambdaSourcePath: dist/cdk/connector/example1.js
- name: example2-subs-ArticlePosted
  eventBusName: community
  source: community
  topic: ArticlePosted
  target: lambda
  targetParams:
    lambdaSourcePath: dist/cdk/connector/example2.js
- name: example-subs-ArticlePosted
  eventBusName: community
  source: community 
  topic: ArticlePosted
  target: sns
  targetParams:
    protocol: email
    subscription: kobtan@seekasia.com

